apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: dipakrasal2009/blog:v1  # 🔹 Replace with your Docker image
          ports:
            - containerPort: 5000  # 🔹 Change if your app runs on another port

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5000          # 🔹 Service port
      targetPort: 5000    # 🔹 Container port
      nodePort: 30080   # 🔹 External port (accessible via <NodeIP>:30080)

